apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # /api/a/xxx -> /xxx trên service api-a
      - path: /api/a(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-a
            port:
              number: 80      # hoặc tên/cổng đúng với Service api-a

      # /api/b/yyy -> /yyy trên service api-b
      - path: /api/b(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-b
            port:
              number: 80      # hoặc tên/cổng đúng với Service api-b
